exclude:
  - aws-ec2-no-public-egress-sgr
  - aws-ec2-no-public-ingress-sgr

  # LOW
  - aws-lambda-enable-tracing
  - aws-cloudwatch-log-group-customer-key
  - aws-dynamodb-table-customer-key


  # MEDIUM
  - aws-cloudfront-enable-logging
  - aws-s3-enable-bucket-logging
